### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by Josh-Hammer** [NicosaurusRex99/Stick-Of-Death#1]
4oz asked me to share with you 
when I have the mod included I get a server crash take it out and no issue 

> ---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.4-1.12.2-anarchy.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  CreativePatchingLoader (CreativeCore_v1.9.19_mc1.12.2.jar)
  BlurPlugin (Blur-1.0.4-14.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.3.0-61.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.1.3.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  CorePlugin (ForgeEndertech-1.12.1-4.3.1.0-build.0071.jar)
  VCTweakerCore (ViesCraftTweaker-1.12.2-2.3.10.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 3/7/18 7:46 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: naturix.stickofdeath.item.ItemBase.func_77629_n_()Z
	at naturix.stickofdeath.item.ItemBase.<init>(ItemBase.java:26)
	at naturix.stickofdeath.ModItems.<clinit>(ModItems.java:10)
	at naturix.stickofdeath.StickOfDeath$RegistrationHandler.registerItems(StickOfDeath.java:53)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_232_RegistrationHandler_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:739)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.4.26-nitradoV3-MC-1000-nH-dP-d-i
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 866441544 bytes (826 MB) / 1490550784 bytes (1421 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 2 total; -Xms256M -Xmx3072M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2613 117 mods loaded, 117 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version                  | Source                                          | Signature                                |
	|:----- |:-------------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                  | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCH   | mcp                        | 9.42                     | minecraft.jar                                   | None                                     |
	| UCH   | FML                        | 8.0.99.99                | minecraft_server.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                      | 14.23.2.2613             | minecraft_server.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | advancedrocketrycore       | 1                        | minecraft.jar                                   | None                                     |
	| UCH   | creativecoredummy          | 1.0.0                    | minecraft.jar                                   | None                                     |
	| UCH   | vctweaker                  | 2.3                      | ViesCraftTweaker-1.12.2-2.3.10.jar              | f2ae887a76e1b521b51bb44cf136918015b5927a |
	| UCH   | openmodscore               | 0.11.5                   | minecraft.jar                                   | None                                     |
	| UCH   | foamfixcore                | 7.7.4                    | minecraft.jar                                   | None                                     |
	| UCH   | actuallyadditions          | 1.12.2-r131              | ActuallyAdditions-1.12.2-r131.jar               | None                                     |
	| UCH   | redstoneflux               | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCH   | cofhcore                   | 4.3.10                   | CoFHCore-1.12.2-4.3.10.5-universal.jar          | None                                     |
	| UCH   | libvulpes                  | 0.2.8.-27                | LibVulpes-1.12.2-0.2.8-27-universal.jar         | None                                     |
	| UCH   | advancedrocketry           | 1.3.0.-61                | AdvancedRocketry-1.12.2-1.3.0-61.jar            | None                                     |
	| UCH   | appliedenergistics2        | rv5-stable-8             | appliedenergistics2-rv5-stable-8.jar            | None                                     |
	| UCH   | bdlib                      | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                    | None                                     |
	| UCH   | ae2stuff                   | 0.7.0.4                  | ae2stuff-0.7.0.4-mc1.12.2.jar                   | None                                     |
	| UCH   | autopackager               | 1.9                      | autopackager-1.9.jar                            | None                                     |
	| UCH   | badwithernocookiereloaded  | 1.12.2-2.12              | badwithernocookiereloaded-1.12.2-2.12.jar       | None                                     |
	| UCH   | crafttweaker               | 4.1.5                    | CraftTweaker2-1.12-4.1.5.jar                    | None                                     |
	| UCH   | mtlib                      | @VERSION@                | MTLib-3.0.2.jar                                 | None                                     |
	| UCH   | modtweaker                 | 4.0.7                    | modtweaker-4.0.7.jar                            | None                                     |
	| UCH   | jei                        | 4.8.5.147                | jei_1.12.2-4.8.5.147.jar                        | None                                     |
	| UCH   | base                       | 3.6.1                    | base-1.12.2-3.6.1.jar                           | None                                     |
	| UCH   | baubles                    | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCH   | betterbuilderswands        | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCH   | betterquesting             | 3.5.239                  | BetterQuesting-3.5.239.jar                      | None                                     |
	| UCH   | bonsaitrees                | 1.0.3                    | bonsaitrees-1.0.3-b67.jar                       | None                                     |
	| UCH   | bookshelf                  | 2.3.528                  | Bookshelf-1.12.2-2.3.528.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | botania                    | r1.10-353                | Botania r1.10-353.jar                           | None                                     |
	| UCH   | mcmultipart                | 2.4.1                    | MCMultiPart-2.4.1.jar                           | None                                     |
	| UCH   | ftbl                       | 4.2.5                    | FTBLib-4.2.5.jar                                | None                                     |
	| UCH   | ftbu                       | 4.2.4                    | FTBUtilities-4.2.4.jar                          | None                                     |
	| UCH   | carryon                    | 1.7.2                    | CarryOn MC1.12.2 v1.7.2.jar                     | None                                     |
	| UCH   | chameleon                  | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCH   | chesttransporter           | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar               | None                                     |
	| UCH   | codechickenlib             | 3.1.5.331                | CodeChickenLib-1.12.2-3.1.5.331-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | cofhworld                  | 1.1.1                    | CoFHWorld-1.12.2-1.1.1.12-universal.jar         | None                                     |
	| UCH   | cyclopscore                | 0.11.4                   | CyclopsCore-1.12.2-0.11.4.jar                   | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | commoncapabilities         | 1.4.0                    | CommonCapabilities-1.12-1.4.0.jar               | None                                     |
	| UCH   | contenttweaker             | 1.12.2-4.4.1             | ContentTweaker-1.12.2-4.4.1.jar                 | None                                     |
	| UCH   | craftingtweaks             | 8.1.6                    | CraftingTweaks_1.12.1-8.1.6.jar                 | None                                     |
	| UCH   | crafttweakerjei            | 2.0.0                    | CraftTweaker2-1.12-4.1.5.jar                    | None                                     |
	| UCH   | creativecore               | 1.9.9                    | CreativeCore_v1.9.19_mc1.12.2.jar               | None                                     |
	| UCH   | darkutils                  | 1.8.195                  | DarkUtils-1.12.2-1.8.195.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | defaultworldgenerator-port | 1.12-2.3                 | DefaultWorldGenerator-port-1.12-2.3.jar         | None                                     |
	| UCH   | shetiphiancore             | 3.5.6                    | shetiphiancore-1.12.0-3.5.6.jar                 | None                                     |
	| UCH   | endertanks                 | 1.6.4                    | endertanks-1.12.0-1.6.4.jar                     | None                                     |
	| UCH   | reborncore                 | 3.6.8.214                | RebornCore-1.12.2-3.6.8.214-universal.jar       | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCH   | engineersworkshop          | 1.0.4.26                 | EngineersWorkshopReborn-1.12.2-1.0.4.26.jar     | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCH   | expandedbonemeal           | 1.2.1                    | expandedbonemeal-1.11-1.2.1.jar                 | None                                     |
	| UCH   | extracells                 | 2.5.11                   | ExtraCells-1.12.2-2.5.11a48.jar                 | None                                     |
	| UCH   | mantle                     | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UCH   | tconstruct                 | 1.12.2-2.9.1.65          | TConstruct-1.12.2-2.9.1.65.jar                  | None                                     |
	| UCH   | extrautils2                | 1.0                      | extrautils2-1.12-1.7.4.jar                      | None                                     |
	| UCH   | zerocore                   | 1.12-0.1.1.0             | zerocore-1.12-0.1.1.0.jar                       | None                                     |
	| UCH   | bigreactors                | 1.12.2-0.4.5.46          | ExtremeReactors-1.12.2-0.4.5.46.jar             | None                                     |
	| UCH   | fastleafdecay              | v14                      | FastLeafDecay-v14.jar                           | None                                     |
	| UCH   | foamfix                    | 0.9.4-1.12.2             | foamfix-0.9.4-1.12.2-anarchy.jar                | None                                     |
	| UCH   | forestry                   | 5.8.0.250                | forestry_1.12.2-5.8.0.250.jar                   | None                                     |
	| UCH   | forgeendertech             | 1.12.1-4.3.1.0           | ForgeEndertech-1.12.1-4.3.1.0-build.0071.jar    | None                                     |
	| UCH   | forgelin                   | 1.6.0                    | Forgelin-1.6.0.jar                              | None                                     |
	| UCH   | pressure                   | 1.3.1.6                  | pressure-1.3.1.6-mc1.12.1.jar                   | None                                     |
	| UCH   | tesla                      | 1.0.63                   | Tesla-1.12.2-1.0.63.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | thermalfoundation          | 2.3.10                   | ThermalFoundation-1.12.2-2.3.10.6-universal.jar | None                                     |
	| UCH   | advgenerators              | 0.9.20.12                | generators-0.9.20.12-mc1.12.2.jar               | None                                     |
	| UCH   | theoneprobe                | 1.4.19                   | theoneprobe-1.12-1.4.19.jar                     | None                                     |
	| UCH   | modularrouters             | 1.12.2-3.1.2             | modular-routers-1.12.2-3.1.2.jar                | None                                     |
	| UCH   | guideapi                   | 1.12-2.1.4-57            | Guide-API-1.12-2.1.4-57.jar                     | None                                     |
	| UCH   | teslacorelib               | 1.0.13                   | tesla-core-lib-1.12-1.0.13.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | industrialforegoing        | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.8.3-122.jar        | None                                     |
	| UCH   | initialinventory           | 2.0.2                    | InitialInventory-3.0.0.jar                      | None                                     |
	| UCH   | integrateddynamics         | 0.11.5                   | IntegratedDynamics-1.12.2-0.11.5.jar            | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | integrateddynamicscompat   | 1.0.0                    | IntegratedDynamics-1.12.2-0.11.5.jar            | None                                     |
	| UCH   | inventorytweaks            | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | ironchest                  | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                 | None                                     |
	| UCH   | journeymap                 | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCH   | justanothersnad            | 1.12-1.0.0.0             | JustAnotherSnad-1.12-1.0.0.0.jar                | None                                     |
	| UCH   | justenoughbuttons          | 1.12-1.2                 | justenoughbuttons-1.12.2-1.2.2-5.jar            | None                                     |
	| UCH   | justenoughdimensions       | 1.5.5                    | justenoughdimensions-1.12.1-1.5.5.jar           | 2b03e1423915a189b8094816baa18f239d576dff |
	| UCH   | loottweaker                | 0.0.7                    | LootTweaker-1.12.2-0.0.7.jar                    | None                                     |
	| UCH   | magicclover                | 1.12-0.7.8               | magicclover-1.12-0.7.8.jar                      | None                                     |
	| UCH   | modelloader                | 1.0.5                    | modelloader-1.0.5.jar                           | None                                     |
	| UCH   | magneticraft               | 2.1.2                    | Magneticraft_1.12-2.1.2.jar                     | None                                     |
	| UCH   | mcjtylib_ng                | 2.6.5                    | mcjtylib-1.12-2.6.5.jar                         | None                                     |
	| UCH   | mininglib                  | 1.1.0                    | mininglib-1.12.1-1.1.0.jar                      | None                                     |
	| UCH   | mist                       | alpha_СЃ_03              | MistWorld_1.12.1_alpha_c_03.jar                 | None                                     |
	| UCH   | md                         | 1.12.2                   | Mob Drops-1.12.2-0.0.1.jar                      | None                                     |
	| UCH   | mobfarm                    | 2.2.1                    | Mob Farm-1.12-2.2.2.jar                         | None                                     |
	| UCH   | mob_grinding_utils         | 0.3.4                    | MobGrindingUtils-0.3.4.jar                      | None                                     |
	| UCH   | naturescompass             | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                 | None                                     |
	| UCH   | recipehandler              | 0.10                     | NoMoreRecipeConflict-0.10(1.12.2).jar           | None                                     |
	| UCH   | openmods                   | 0.11.5                   | OpenModsLib-1.12.2-0.11.5.jar                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCH   | openblocks                 | 1.7.6                    | OpenBlocks-1.12.2-1.7.6.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCH   | pearcelmod                 | 1.12.1-4.1.2             | pearcelmod-1.12.1-4.1.2.jar                     | None                                     |
	| UCH   | placebo                    | 1.3.0                    | Placebo-1.12.2-1.3.0.jar                        | None                                     |
	| UCH   | proxy                      | 0.9.1.4                  | proxy-0.9.1.4-mc1.12.jar                        | None                                     |
	| UCH   | randomthings               | 4.1.3                    | RandomThings-MC1.12.2-4.1.3.jar                 | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCH   | xreliquary                 | 1.12.2-1.3.4.753         | Reliquary-1.12.2-1.3.4.753.jar                  | None                                     |
	| UCH   | scavenge                   | 1.4                      | Scavenge V1.12-1.6.jar                          | None                                     |
	| UCH   | simpleharvest              | 1.07                     | simpleharvest-1.07.jar                          | None                                     |
	| UCH   | spectrite                  | 1.6.5                    | spectrite-1.6.5.jar                             | 00119cfc089819bbcd2f9166a50c7f3df88ded78 |
	| UCH   | bq_standard                | CI_MOD_VERSION           | StandardExpansion-3.4.138.jar                   | None                                     |
	| UCH   | stickofdeath               | 1.12.2.1                 | stickofdeath-1.12.2.1.jar                       | None                                     |
	| UCH   | stimulus                   | 1.12.2-1.1.0             | stimulus-1.12.2-1.1.0.jar                       | None                                     |
	| UCH   | storagedrawers             | 1.12-5.2.5               | StorageDrawers-1.12.2-5.3.5.jar                 | None                                     |
	| UCH   | thermalcultivation         | 0.1.5                    | ThermalCultivation-1.12.2-0.1.5.3-universal.jar | None                                     |
	| UCH   | thermaldynamics            | 2.3.10                   | ThermalDynamics-1.12.2-2.3.10.4-universal.jar   | None                                     |
	| UCH   | thermalexpansion           | 5.3.10                   | ThermalExpansion-1.12.2-5.3.10.15-universal.jar | None                                     |
	| UCH   | tombmanygraves             | @VERSION@                | TombManyGraves-1.12-4.0.2.jar                   | None                                     |
	| UCH   | vc                         | 5.6.1                    | ViesCraft-1.12.2-5.6.1.jar                      | None                                     |
	| UCH   | wanionlib                  | 1.12.2-1.5               | WanionLib-1.12.2-1.5.jar                        | None                                     |
	| UCH   | waterstrainer              | 3.2.0                    | WaterStrainer-1.12-3.2.0.jar                    | None                                     |
	| UCH   | woot                       | 1.12.2-1.0.0             | woot-1.12.2-1.0.0.jar                           | None                                     |
	| UCH   | xnet                       | 1.6.7                    | xnet-1.12-1.6.7.jar                             | None                                     |
	| UCH   | teslacorelib_registries    | 1.0.13                   | tesla-core-lib-1.12-1.0.13.jar                  | None                                     |
	| UCH   | unidict                    | 1.12.2-2.3.3             | UniDict-1.12.2-2.3.3.jar                        | None                                     |

	Loaded coremods (and transformers): 
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.4-1.12.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  shetiphian.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
CreativePatchingLoader (CreativeCore_v1.9.19_mc1.12.2.jar)
  
BlurPlugin (Blur-1.0.4-14.jar)
  com.tterrag.blur.BlurTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.3.0-61.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.12.2-4.1.3.jar)
  lumien.randomthings.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
CorePlugin (ForgeEndertech-1.12.1-4.3.1.0-build.0071.jar)
  
VCTweakerCore (ViesCraftTweaker-1.12.2-2.3.10.jar)
  se.gory_moon.vctweaker.asm.VCTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  openmods.core.OpenModsClassTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:ENABLED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv5-stable-8 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (33) from ActuallyAdditions-1.12.2-r131.jar
		* appliedenergistics2|API (rv5) from appliedenergistics2-rv5-stable-8.jar
		* Base|API (1.0.0) from base-1.12.2-3.6.1.jar
		* Baubles|API (1.4.0.2) from mininglib-1.12.1-1.1.0.jar
		* BetterQuesting|API (3.0) from BetterQuesting-3.5.239.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.12.2-0.4.5.46.jar
		* BotaniaAPI (89) from Botania r1.10-353.jar
		* chesttransporter|api (2) from ChestTransporter-1.12.2-2.8.8.jar
		* cofhapi (2.2.0) from CoFHCore-1.12.2-4.3.10.5-universal.jar
		* cofhapi|block (2.2.0) from CoFHCore-1.12.2-4.3.10.5-universal.jar
		* cofhapi|core (2.2.0) from CoFHCore-1.12.2-4.3.10.5-universal.jar
		* cofhapi|item (2.2.0) from CoFHCore-1.12.2-4.3.10.5-universal.jar
		* cofhapi|tileentity (2.2.0) from CoFHCore-1.12.2-4.3.10.5-universal.jar
		* cofhapi|util (2.2.0) from CoFHCore-1.12.2-4.3.10.5-universal.jar
		* commoncapabilities|api (0.0.1) from CommonCapabilities-1.12-1.4.0.jar
		* CraftingTweaks|API (4.1) from CraftingTweaks_1.12.1-8.1.6.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|core (5.7.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|farming (5.8.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|food (1.1.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.8.0.250.jar
		* ForestryAPI|world (2.1.0) from forestry_1.12.2-5.8.0.250.jar
		* Guide-API|API (2.0.0) from Guide-API-1.12-2.1.4-57.jar
		* industrialforegoingapi (3) from industrialforegoing-1.12.2-1.8.3-122.jar
		* integrateddynamics|api (0.2.0) from IntegratedDynamics-1.12.2-0.11.5.jar
		* jeresources|API (0.8.5.27) from JustEnoughResources-1.12.2-0.8.5.27.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.2.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.8.5.147.jar
		* MCX Model Loader (1.0.0) from modelloader-1.0.5.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.8-mc1.12.1.jar
		* openblocks|api (1.2) from OpenBlocks-1.12.2-1.7.6.jar
		* pressureAPI (1.3.1.6) from pressure-1.3.1.6-mc1.12.1.jar
		* reborncoreAPI (3.6.8.214) from RebornCore-1.12.2-3.6.8.214-universal.jar
		* reborncoreAPI|Power (3.6.8.214) from RebornCore-1.12.2-3.6.8.214-universal.jar
		* reborncoreAPI|Recipe (3.6.8.214) from RebornCore-1.12.2-3.6.8.214-universal.jar
		* reborncoreAPI|Tile (3.6.8.214) from RebornCore-1.12.2-3.6.8.214-universal.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.3.5.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.3.5.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.3.5.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.3.5.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.3.5.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.3.5.jar
		* theoneprobe_api (1.4.4) from theoneprobe-1.12-1.4.19.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.12-0.1.1.0.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.12-0.1.1.0.jar
		* zerocore|API|multiblock|tier (1.10.2-0.0.2) from zerocore-1.12-0.1.1.0.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.12-0.1.1.0.jar
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.6.8.214
		Runtime Debofucsation 1
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

>

**Comment by NicosaurusRex99** [comment]
**Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.4-1.12.2-anarchy.jar)**
Please try this and then tell me the result

**Comment by NicosaurusRex99** [comment]
fixed in update 1d7894a
